name: variables
runs:
  using: composite
  steps:
    - run: |
        echo "Configurando las variables..."
        echo "Usuario: ${{ secrets.DB_USER_DEV }}, Clave:${{ secrets.DB_PASS_DEV }}, Key: ${{ secrets.API_KEY_DEV }}"
      shell: bash